Repository greenbone/gsa, pull requests merged in 2021-06, with the labels that each got.

#2948 Avoid cross origin forgery by using same-site cookie
  CHANGELOG.md
  gsad/src/gsad_http.c
Labels: port-to-21.04, port-to-21.10, port-to-master

#2954 Allow to add ssh elevate credential to target dialog and display elevate credential in details
  CHANGELOG.md
  gsa/public/locales/gsa-de.json
  gsa/src/gmp/commands/targets.js
  gsa/src/gmp/models/credential.js
  gsa/src/gmp/models/target.js
  gsa/src/web/pages/targets/component.js
  gsa/src/web/pages/targets/details.js
  gsa/src/web/pages/targets/dialog.js
  gsad/src/gsad.c
  gsad/src/gsad_gmp.c
Labels: port-to-21.10

#2949 Properly space and linebreak roles and groups in users table row
  CHANGELOG.md
  gsa/src/web/components/layout/__tests__/__snapshots__/horizontalsep.js.snap
  gsa/src/web/components/layout/__tests__/horizontalsep.js
  gsa/src/web/components/layout/horizontalsep.js
  gsa/src/web/pages/users/row.js
Labels: port-to-21.04, port-to-21.10, port-to-master

#2960 Use deprecation tag in NVT details
  CHANGELOG.md
  gsa/public/locales/gsa-de.json
  gsa/src/gmp/models/__tests__/nvt.js
  gsa/src/gmp/models/nvt.js
  gsa/src/web/pages/nvts/details.js
Labels: port-to-21.10, port-to-master

#2974 Add target dialog and ssh elevate credential related tests
  gsa/src/gmp/commands/__tests__/target.js
  gsa/src/gmp/commands/targets.js
  gsa/src/web/pages/targets/__tests__/details.js
  gsa/src/web/pages/targets/__tests__/dialog.js
  gsa/src/web/pages/targets/dialog.js
Labels: port-to-21.10

#2994 Disallow using the same credential for ssh and elevate credential in targets
  CHANGELOG.md
  gsa/src/web/pages/targets/__tests__/dialog.js
  gsa/src/web/pages/targets/dialog.js
Labels: port-to-21.10

#2980 Show xref type in NVT details
  CHANGELOG.md
  gsa/src/web/pages/nvts/references.js
Labels: port-to-21.04, port-to-21.10, port-to-master

#2996 Added SSH Elevate credential to target row
  CHANGELOG.md
  gsa/public/locales/gsa-de.json
  gsa/src/web/pages/targets/__tests__/row.js
  gsa/src/web/pages/targets/row.js
Labels: port-to-21.10

#3008 Fix copyright header for recently added target tests
  gsa/src/web/pages/targets/__tests__/dialog.js
  gsa/src/web/pages/targets/__tests__/row.js
Labels: port-to-21.10

#3010 SSH elevate credential should not appear in dropdown for SSH credential
  gsa/src/web/pages/targets/__tests__/dialog.js
  gsa/src/web/pages/targets/component.js
  gsa/src/web/pages/targets/dialog.js
Labels: port-to-21.10

#3007 Replace localtime with localtime_r
  gsad/src/gsad_base.c
  gsad/src/gsad_gmp.c
  gsad/src/gsad_http.c
Labels: port-to-20.08, port-to-21.04, port-to-21.10

#3015 Prevent crash on alert listpage due to undefined subobjects
  gsa/src/gmp/models/alert.js
  gsa/src/web/pages/alerts/condition.js
  gsa/src/web/pages/alerts/details.js
  gsa/src/web/pages/alerts/method.js
Labels: port-to-21.10

#3018 Replace gmtime with gmtime_r
  gsad/src/gsad_gmp.c
Labels: port-to-20.08, port-to-21.04

#3031 Initialize severity value with 0 in powerfilter
  CHANGELOG.md
  gsa/src/web/components/powerfilter/__tests__/__snapshots__/severityvaluesgroup.js.snap
  gsa/src/web/components/powerfilter/__tests__/severityvaluesgroup.js
  gsa/src/web/components/powerfilter/severityvaluesgroup.js
  gsa/src/web/pages/results/filterdialog.js
Labels: port-to-21.04, port-to-21.10

#3024 Add listpage and detailspage tests
  gsa/src/web/entity/__tests__/box.js
  gsa/src/web/entity/__tests__/note.js
  gsa/src/web/entity/__tests__/override.js
  gsa/src/web/entity/box.js
  gsa/src/web/pages/credentials/__tests__/detailspage.js
  gsa/src/web/pages/credentials/__tests__/listpage.js
  gsa/src/web/pages/credentials/detailspage.js
  gsa/src/web/pages/credentials/listpage.js
  gsa/src/web/pages/notes/__tests__/detailspage.js
  gsa/src/web/pages/notes/__tests__/listpage.js
  gsa/src/web/pages/notes/detailspage.js
  gsa/src/web/pages/notes/listpage.js
  gsa/src/web/pages/nvts/__tests__/detailspage.js
  gsa/src/web/pages/nvts/__tests__/listpage.js
  gsa/src/web/pages/nvts/detailspage.js
  gsa/src/web/pages/nvts/listpage.js
  gsa/src/web/pages/overrides/__tests__/detailspage.js
  gsa/src/web/pages/overrides/__tests__/listpage.js
  gsa/src/web/pages/overrides/detailspage.js
  gsa/src/web/pages/overrides/listpage.js
  gsa/src/web/pages/results/__tests__/detailspage.js
  gsa/src/web/pages/results/__tests__/listpage.js
  gsa/src/web/pages/results/detailspage.js
  gsa/src/web/pages/results/listpage.js
  gsa/src/web/pages/schedules/__tests__/detailspage.js
  gsa/src/web/pages/schedules/__tests__/listpage.js
  gsa/src/web/pages/schedules/detailspage.js
  gsa/src/web/pages/schedules/listpage.js
  gsa/src/web/pages/targets/__tests__/detailspage.js
  gsa/src/web/pages/targets/__tests__/listpage.js
  gsa/src/web/pages/targets/detailspage.js
  gsa/src/web/pages/targets/listpage.js
Labels: port-to-21.10

#3045 Use better defaults for installation locations
  CHANGELOG.md
  gsad/CMakeLists.txt
  gsad/config/CMakeLists.txt
  gsad/config/gsad.default
  gsad/config/gsad.service.in
Labels: port-to-20.08, port-to-21.10
