Repository greenbone/gsa, pull requests merged in 2021-04, with the labels that each got.

#2840 Show StartIcon for scheduled tasks on task listpage
  CHANGELOG.md
  gsa/src/web/pages/tasks/__tests__/actions.js
  gsa/src/web/pages/tasks/actions.js
Labels: port-to-master

#2846 Allow underscores and hyphens in host parameters
  CHANGELOG.md
  gsad/src/gsad.c
Labels: port-to-21.04, port-to-master

#2867 Pre-select greenbone sensor as default scanner type
  CHANGELOG.md
  gsa/src/web/pages/scanners/dialog.js
Labels: port-to-master

#2880 Sort host, os and vulns listpage by descending severity
  CHANGELOG.md
  gsa/src/web/pages/hosts/listpage.js
  gsa/src/web/pages/operatingsystems/listpage.js
  gsa/src/web/pages/vulns/listpage.js
Labels: port-to-20.08

#2883 Don't show word cloud as default in result dashboard
  CHANGELOG.md
  gsa/src/web/pages/results/dashboard/index.js
Labels: port-to-master
