Repository greenbone/gsa, pull requests merged in 2021-05, with the labels that each got.

#2891 Fix setting Radius secret key in dialog
  CHANGELOG.md
  gsa/package.json
  gsa/src/web/pages/radius/__tests__/dialog.js
  gsa/src/web/pages/radius/dialog.js
Labels: port-to-master

#2905 Fix changing Trend and Select for NVT-families and whole selection only
  CHANGELOG.md
  gsa/src/web/pages/scanconfigs/nvtfamilies.js
Labels: port-to-21.10, port-to-master

#2914 Fix unable to edit schedules with number only name
  CHANGELOG.md
  gsa/src/web/pages/schedules/dialog.js
Labels: bug, port-to-21.10, port-to-master

#2919 Remove OVAL Definitions detailspage and listpage
  CHANGELOG.md
  gsa/CMakeLists.txt
  gsa/src/web/components/bar/menubar.js
  gsa/src/web/pages/ovaldefs/dashboard/classdisplay.js
  gsa/src/web/pages/ovaldefs/dashboard/createddisplay.js
  gsa/src/web/pages/ovaldefs/dashboard/cvssdisplay.js
  gsa/src/web/pages/ovaldefs/dashboard/index.js
  gsa/src/web/pages/ovaldefs/dashboard/loaders.js
  gsa/src/web/pages/ovaldefs/dashboard/severityclassdisplay.js
  gsa/src/web/pages/ovaldefs/details.js
  gsa/src/web/pages/ovaldefs/detailspage.js
  gsa/src/web/pages/ovaldefs/filterdialog.js
  gsa/src/web/pages/ovaldefs/listpage.js
  gsa/src/web/pages/ovaldefs/row.js
  gsa/src/web/pages/ovaldefs/table.js
  gsa/src/web/pages/start/dashboard.js
  gsa/src/web/routes.js
Labels: port-to-master

#2921 Remove more occurences of OVAL Definitions
  CHANGELOG.md
  gsa/CMakeLists.txt
  gsa/src/gmp/capabilities/__tests__/capabilities.js
  gsa/src/gmp/capabilities/capabilities.js
  gsa/src/gmp/commands/ovaldefs.js
  gsa/src/gmp/commands/users.js
  gsa/src/gmp/gmp.js
  gsa/src/gmp/models/__tests__/ovaldef.js
  gsa/src/gmp/models/__tests__/secinfo.js
  gsa/src/gmp/models/filter.js
  gsa/src/gmp/models/ovaldef.js
  gsa/src/gmp/models/scanner.js
  gsa/src/gmp/models/secinfo.js
  gsa/src/web/pages/scanners/details.js
Labels: port-to-master

#2924 Fix "Pre-select greenbone sensor as default scanner type"
  CHANGELOG.md
  gsa/src/web/pages/scanners/component.js
Labels: port-to-21.10, port-to-master

#2931 Fix setting whether to include related resources in new permissions
  CHANGELOG.md
  gsa/src/web/pages/permissions/multipledialog.js
Labels: port-to-21.04, port-to-21.10, port-to-master

#2923 Remove remaining OVAL Definitions occurences
  CHANGELOG.md
  gsa/CMakeLists.txt
  gsa/public/locales/gsa-de.json
  gsa/src/gmp/utils/entitytype.js
  gsa/src/web/components/dashboard/display/utils.js
  gsa/src/web/components/icon/__tests__/ovaldeficon.js
  gsa/src/web/components/icon/ovaldeficon.js
  gsa/src/web/components/icon/svg/ovaldef.svg
  gsa/src/web/pages/alerts/secinfoeventpart.js
  gsa/src/web/pages/extras/__tests__/feedstatuspage.js
  gsa/src/web/pages/extras/feedstatuspage.js
  gsa/src/web/pages/omp.js
  gsa/src/web/pages/results/details.js
  gsa/src/web/pages/tags/component.js
  gsa/src/web/pages/usersettings/dialog.js
  gsa/src/web/pages/usersettings/filterpart.js
  gsa/src/web/pages/usersettings/usersettingspage.js
  gsa/src/web/store/entities/__tests__/ovaldefs.js
  gsa/src/web/store/entities/__tests__/reducers.js
  gsa/src/web/store/entities/ovaldefs.js
  gsa/src/web/store/entities/reducers.js
  gsa/src/web/utils/render.js
Labels: port-to-master

#2934 Fix loading NVT information in result details
  CHANGELOG.md
  gsa/src/web/pages/results/detailspage.js
Labels: port-to-21.10

#2944 Fall back to cvss_base when severity subelement is missing from NVT severities
  CHANGELOG.md
  gsa/src/gmp/models/__tests__/nvt.js
  gsa/src/gmp/models/nvt.js
Labels: port-to-21.10, port-to-master
