Repository greenbone/gsa, pull requests merged in 2021-08, with the labels that each got.

#3101 Update RELEASE.md
  RELEASE.md
Labels: port-to-21.04, port-to-master

#3113 Use the correct DIR for the pid location
  gsad/config/gsad.service.in
Labels: port-to-20.08, port-to-master

#3117 Remove duplicated line from config
  gsad/config/gsad.service.in
Labels: port-to-20.08, port-to-master

#3120 [AP1581] Don't crash target table when port_list is undefined (fix trashcan)
  CHANGELOG.md
  gsa/src/web/pages/targets/__tests__/row.js
  gsa/src/web/pages/targets/row.js
Labels: port-to-master

#3124 [AP1032] Show dead hosts as possible reason in empty report when scan finishes
  CHANGELOG.md
  gsa/src/web/pages/reports/details/emptyreport.js
Labels: port-to-master, port-to-21.04

#3130 Add tests for credential and schedule dialog
  gsa/src/web/pages/credentials/__tests__/dialog.js
  gsa/src/web/pages/schedules/__tests__/dialog.js
Labels: port-to-master
