Repository greenbone/gsa, pull requests merged in 2021-09, with the labels that each got.

#3154 [AP1447] Change conditions for enabling CreateTicketIcon on results detailspage
  CHANGELOG.md
  gsa/public/locales/gsa-de.json
  gsa/src/web/pages/results/detailspage.js
Labels: port-to-master

#3149 Add new handler for single performance report
  CHANGELOG.md
  gsad/src/gsad.c
  gsad/src/gsad_gmp.c
  gsad/src/gsad_gmp.h
  gsad/src/gsad_http_handler.c
Labels: port-to-master

#3157 [AP1032] Fix condition for dead host notification in empty report
  CHANGELOG.md
  gsa/src/web/pages/reports/details/emptyreport.js
Labels: port-to-master, port-to-21.04

#3160 [AP1571] Add license command and update page
  CHANGELOG.md
  gsa/public/locales/gsa-de.json
  gsa/src/gmp/commands/__tests__/license.js
  gsa/src/gmp/commands/license.js
  gsa/src/gmp/gmp.js
  gsa/src/web/components/bar/menubar.js
  gsa/src/web/pages/licenses/__tests__/licensepage.js
  gsa/src/web/pages/licenses/licensepage.js
  gsa/src/web/pages/page.js
  gsa/src/web/routes.js
Labels: feature

#3164 Require node.js >= 14
  .docker/testing/Dockerfile
  .github/workflows/ci-js.yml
  CHANGELOG.md
  INSTALL.md
  gsa/CMakeLists.txt
  gsa/package.json
Labels: dependencies
