Repository greenbone/gsa, pull requests merged in 2021-07, with the labels that each got.

#3052 Use UNSET_VALUE as default for relation of severity values in powerfilter
  CHANGELOG.md
  gsa/src/web/components/powerfilter/__tests__/relationselector.js
  gsa/src/web/components/powerfilter/__tests__/severityvaluesgroup.js
  gsa/src/web/components/powerfilter/relationselector.js
  gsa/src/web/components/powerfilter/severityvaluesgroup.js
Labels: port-to-21.04, port-to-21.10

#3068 CSP header adjustments
  CHANGELOG.md
  gsa/package.json
  gsad/src/gsad.c
Labels: port-to-21.04, port-to-master

#3057 Fix setting/displaying timeout in EditNvtDetailsDialog
  CHANGELOG.md
  gsa/src/web/pages/scanconfigs/editnvtdetailsdialog.js
Labels: port-to-21.04, port-to-21.10

#3062 Add missing listpage and detailspage tests
  gsa/src/web/pages/alerts/__tests__/detailspage.js
  gsa/src/web/pages/alerts/__tests__/listpage.js
  gsa/src/web/pages/alerts/detailspage.js
  gsa/src/web/pages/alerts/listpage.js
  gsa/src/web/pages/cpes/__tests__/detailspage.js
  gsa/src/web/pages/cpes/__tests__/listpage.js
  gsa/src/web/pages/cpes/detailspage.js
  gsa/src/web/pages/cpes/listpage.js
  gsa/src/web/pages/cves/__tests__/listpage.js
  gsa/src/web/pages/cves/listpage.js
  gsa/src/web/pages/hosts/__tests__/detailspage.js
  gsa/src/web/pages/hosts/__tests__/listpage.js
  gsa/src/web/pages/hosts/detailspage.js
  gsa/src/web/pages/hosts/listpage.js
Labels: port-to-21.04

#3082 Avoid caching of the index.html page
  CHANGELOG.md
  gsad/src/gsad_http_handler.c
Labels: port-to-21.04, port-to-master

#3085 Make SSH elevate credential optional in gsad
  CHANGELOG.md
  gsad/src/gsad_gmp.c
Labels: port-to-21.04

#3091 [AP1596] Add information about elevate credential being experimental
  CHANGELOG.md
  gsa/public/locales/gsa-de.json
  gsa/src/web/components/icon/__tests__/infoicon.js
  gsa/src/web/components/icon/infoicon.js
  gsa/src/web/components/icon/svg/info.svg
  gsa/src/web/pages/targets/dialog.js
Labels: port-to-master

#3095 Further restrict content security policy
  CHANGELOG.md
  gsad/src/gsad.c
Labels: port-to-21.04, port-to-master
